import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import ProviderWrapper from './components/ProviderWrapper';
import NextTopLoader from 'nextjs-toploader';
import AuthWrapper from './components/NextAuthProviderWrapper';

const fontName = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={fontName.className}>
                <Toaster
                    position='top-center'
                />
                <NextTopLoader color='#00db96' zIndex={9999} />
                <AuthWrapper>
                    <ProviderWrapper>
                        {children}
                    </ProviderWrapper>
                </AuthWrapper>
            </body>
        </html>
    )
}