import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import connectDatabase from '@/lib/Database';
import { Toaster } from 'react-hot-toast';
import ProviderWrapper from './components/ProviderWrapper';

const quicksand = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    connectDatabase();
    return (
        <html lang="en">
            <body className={quicksand.className}>
                <Toaster
                    position='top-center'
                />
                <ProviderWrapper>
                    {children}
                </ProviderWrapper>
            </body>
        </html>
    )
}